### ISSUE TITLE
Slack doesn't consistently print the output of stdout?

### ISSUE THREAD

**Issue by ezgoodnight** [slackhq/hubot-slack#172]
I opened an issue with the author of this simple script to run child_process:

https://github.com/sapg/hubot-scripts/issues/1

The shell adapter for my hubot returns as I would expect when I run scripts, but Slack does not seem to print the results consistently. For instance, as I detail in the above link:

```
module.exports = (robot) ->
 robot.respond /find(.*)$/i, (msg) ->
    hostname = msg.match[1]
    @exec = require('child_process').exec
    command = "locate -i #{hostname}"

    msg.send "Looking up #{hostname}..."
    msg.send "This is the command #{command}."

    @exec command, (error, stdout, stderr) ->
      msg.send error
      msg.send stdout
      msg.send stderr
      console.log(stdout)

```

When I use this in the hubot shell adapter it returns what I expect. When I use it in Slack I get a result when I search for my username but not anything else.

I don't think it's a problem with the script, but either with Slack, Hubot, or the Adapter. Any thoughts?

**Comment by ezgoodnight** [comment]
While there's something funny going on and Slack doesn't return everything that the shell returns, it's apparently a nightmare to pipe shell commands in coffeescript/node and that's a big part of what's wrong here.

**Comment by evansolomon** [comment]
I don't think I understand the exact issue here.  It would be helpful to have a reproducible example or at least more context.

> it's apparently a nightmare to pipe shell commands in coffeescript/node and that's a big part of what's wrong here

It shouldn't really be.  Your code looks like it should be fine.  Only weird thing is setting `@exec`.  You're probably betting off doing `exec = require('child_process').exec` at the top of your file and then `exec command, ...`.  That said, I may not 100% know what you mean by piping commands because I don't see any pipes here (unless they're in the matched message?).

**Comment by ezgoodnight** [comment]
Hey, Evan,

Yes, just to test I used the shell script: 

`locate -i #{Argument} | grep -i something | head -n 20`

This lead to the error

`locate: I/O error while writing to standard output: Broken pipe`

Although I got quite a few problems working with this. I'm seeing other people are having issues working with node and more complicated shell commands/output to stdout:

http://stackoverflow.com/questions/9777215/running-a-shell-command-from-node-js-without-buffering-output

Although I'm not an expert by any means. If you think I can get this to work, I appreciate the help.

Here's what I had tried:
```
module.exports = (robot) ->
 robot.respond /find (.*)$/i, (msg) ->
    Argument = msg.match[1]
    @exec = require('child_process').exec
    command = "locate -i #{Argument} | head -n 20"

    msg.send "Looking up #{Argument}..."
    msg.send "This is the command #{command}."

    @exec command, (error, stdout, stderr) ->
      msg.send error
      msg.send stdout
      msg.send stderr
      console.log(stdout)

```
In the shell, I get the following:
hubot> hubot find vinyl
hubot> Looking up vinyl...
This is the command locate -i vinyl | head -n 20.
null
/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/mem-fs/node_modules/vinyl
/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/mem-fs/node_modules/vinyl-file
/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/mem-fs/node_modules/vinyl/README.md
/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/mem-fs/node_modules/vinyl/index.js


locate: I/O error while writing to standard output: Broken pipe

/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/mem-fs/node_modules/vinyl
/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/mem-fs/node_modules/vinyl-file
/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/mem-fs/node_modules/vinyl/README.md
/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/mem-fs/node_modules/vinyl/index.js
```

In Slack, I get only this:
```
hubot BOT [4:47 PM] 
Looking up vinyl...

hubot BOT [4:47 PM]
This is the command locate -i vinyl | head -n 20.
```

And no output from the command to Slack. Thoughts?

**Comment by evansolomon** [comment]
I would suggest taking out the console.log.  That's definitely going to look different in the terminal adapter because in that case you'll see actual messages and anything written to stdout/stderr.  In the Slack case (or any other chat adapter) you're not going to see things written to stdout/err.

As for the broken pipe error, that is relatively common in cases where you're piping to something like `head -n #` because the right side of the pipe can exit while the left side of the pipe is still going.  I'm not 100% sure this is what's going on in your case, but it has a lot in common with it.  There's a similar error described [here](http://superuser.com/questions/554855/how-can-i-fix-a-broken-pipe-error).

**Comment by ezgoodnight** [comment]
I only added the console.log to try and see if it was outputting anything different (it wasn't) and removing it didn't make a difference except I got one output from the command in place of two. The output of stdout doesn't get sent to Slack with that script, nor several others. When I search for my username without the pipe, it will output to Slack, but only then. Even `ls` and `pwd` do not output to Slack.

That link is good information, but it mostly amounts to "don't worry about it." The only thing I can gather from it is that the broken pipe error is probably not what's creating the issue.

**Comment by ezgoodnight** [comment]
Just this one also doesn't output to Slack but does output to the shell adapter as expected.

I suppose my original thought was correct that this is something wrong with the Slack adapter or (more likely) something wrong with my implementation of the hubot.

```
module.exports = (robot) ->
 robot.respond /pwd/i, (msg) ->
    exec = require('child_process').exec
    command = "pwd"

    msg.send "This is the command #{command}."

    exec command, (error, stdout, stderr) ->
      msg.send error
      msg.send stdout
      msg.send stderr

```

**Comment by evansolomon** [comment]
I will be kind of surprised if this works, but can you try adding `toString()` to the outputs you send (e.g. `msg.send stdout.toString()`)

**Comment by ezgoodnight** [comment]
```
module.exports = (robot) ->
 robot.respond /pwd/i, (msg) ->
    exec = require('child_process').exec
    command = "pwd"

    msg.send "This is the command #{command}."

    exec command, (error, stdout, stderr) ->
      msg.send error
#      msg.send stdout
      msg.send stdout.toString()
      msg.send stderr

```

Still negative on the return from `pwd` to Slack.

**Comment by evansolomon** [comment]
I setup a similar script.  The answer is actually pretty simple once you look at the error logs: you're trying to `msg.send()` nulls.

```
[Wed Apr 01 2015 11:16:15 GMT-0700 (PDT)] ERROR TypeError: Cannot read property 'length' of null
  at SlackBot.send (/Users/evan/code/hubots/hubot/node_modules/hubot-slack/src/slack.coffee:243:16)
  at Response.send (/Users/evan/code/hubots/hubot/node_modules/hubot/src/response.coffee:22:5)
  at /Users/evan/code/hubots/hubot/scripts/example.coffee:10:11
  at ChildProcess.exithandler (child_process.js:735:7)
  at ChildProcess.emit (events.js:110:17)
  at maybeClose (child_process.js:1008:16)
  at Socket.<anonymous> (child_process.js:1176:11)
  at Socket.emit (events.js:107:17)
  at Pipe.close (net.js:476:12)
```

**Comment by evansolomon** [comment]
Example of a working script

```coffeescript
{exec} = require 'child_process'
module.exports = (robot) ->
  robot.respond /pwd/i, (msg) ->
    command = "pwd"

    msg.send "This is the command #{command}."

    exec command, (error, stdout, stderr) ->
      msg.send error if error
      msg.send stdout if stdout
      msg.send stderr if stderr
```

**Comment by ezgoodnight** [comment]
This absolutely does work for me, but I'm trying to dissect why. Don't know what's relevant.

You're calling up the object differently, outside of the function hubot performs.
It's also requiring `child_process` different. The variable is not `child_process.exec` which is the function inside `child_process`. I don't understand why this works but I am relatively new to this.

I also have no idea what that log is telling me. I'll have to compare it to an output from one using your script.

**Comment by evansolomon** [comment]
> You're calling up the object differently, outside of the function hubot performs.
It's also requiring child_process different. The variable is not child_process.exec which is the function inside child_process.

Sorry, those differences are just because I wrote it separately from yours.  `{thing} = whatever` is just Coffeescript sugar for `thing = whatever.thing`, and it's outside of the callback just because that's a more common style.

> I also have no idea what that log is telling me

The log is telling you that there's a `null` when there shouldn't be.  The underlying reason is that the data is sent over a web socket and has to be string-like.

**Comment by ezgoodnight** [comment]
You've been really helpful, Evan.

It makes sense you were trying to accomplish this by passing the data to the string function. I'm unclear what about these slight differences returns strings when my script is almost identical (at least, to me) and it returns a string.

My issue is solved, I'd say, but if you can explain why yours returns the right thing, it would save me hours of figuring out WHY.

**Comment by evansolomon** [comment]
> I'm unclear what about these slight differences returns strings when my script is almost identical (at least, to me) and it returns a string.

In JavaScript everything is an object except when it's not.  Nulls are weird things that are mostly not objects, but just to make it fun `typeof null === 'object'` for legacy reasons.

Because nulls are not really objects, they don't have properties.  Trying to access a property of null (like a toString method) throws a type error.  This can seem quite weird coming from other languages like Ruby where `nil.to_s` is totally fine.  But, JavaScript.

Applying this to the 3 versions we've had of your script goes something like this.

First, `msg.send variableThatIsNull` makes it's way through the call stack until eventually we try to count how many messages we have so that we can get ready to send them to the server[0].  To do that, we read `variableThatIsNull.length`, which throws a type error because nulls don't have a length (or any other property).

Second, `msg.send variableThatIsNull.toString()` throws a type error immediately because nulls don't have properties, so they certainly don't have methods.

Third, `msg.send variableThatIsNull if variableThatIsNull` safely does nothing because the conditional check fails and `msg.send` is never called (until we find a variableThatIsNotNull).

[0] Earlier I said that the length check came when sending it to the socket.  Actually the issue here comes when dealing with multiple messages.  There are some ways the adapter could be more defensive in these cases, though I'm on the fence about whether calling `msg.send null` is really something that should look okay to do.

**Comment by ezgoodnight** [comment]
You've been awesome. Thanks for all of your help.

**Comment by sandeepmp** [comment]
Hi @evansolomon 
Is there a way we can pass dynamic values to the command?

For example, 
command = "#{data_from_loop}"?
