### ISSUE TITLE
Object is not a function

### ISSUE THREAD

**Issue by SamHam** [slackhq/hubot-slack#197]
Hi,I keep getting the below issue 'Object is not a function' when I load the Hubot-slack module.

Can anyone help with this?

mybot> [Tue Jun 02 2015 19:15:23 GMT+0100 (BST)] ERROR Error loading scripts from npm package - TypeError: object is not a function
  at Robot.loadExternalScripts (/home/sam/mybot/node_modules/hubot/src/robot.coffee:263:11, <js>:212:39)
  at /home/sam/mybot/node_modules/hubot/bin/hubot:119:11, <js>:123:26
  at fs.js:334:14
  at FSReqWrap.oncomplete (fs.js:95:15)

Cheers,
Sam

**Comment by skippednote** [comment]
You don't have to add `hubot-slack` in your `external-scripts.json`.

**Comment by technicalpickles** [comment]
@SamHam I'm going to close, because @skippednote touched on why this particular error. Please let me know if you are still having problems!

**Comment by farski** [comment]
@technicalpickles Just in case someone else ends up here... I was having an issue where Hubot was starting but not connecting to Slack, so I tried adding `hubot-slack` to `external-scripts.json`, and obviously got this error. The issue was my boot script was using the wrong adapter; it needed `--adapter slack`
