### ISSUE TITLE
Hubt should be a dependency rather than a devDependency

### ISSUE THREAD

**Issue by ajwhite** [slackhq/hubot-slack#225]
Noticed that `hubot` wasn't installed when only installing production deps:

https://github.com/slackhq/hubot-slack/blob/master/package.json#L60

This should be up in the `dependencies` rather than the `devDependencies`

**Comment by technicalpickles** [comment]
Are you running into problems with the way things are now with running hubot?

In a hubot instance, you'd have a package.json that'd depend on hubot and the adapter. hubot then loads the adapter.

I think it probably is actually a peerDependency, since you'd want hubot-slack to be installed as a sibling, rather bundling hubot under hubot-slack.

**Comment by ajwhite** [comment]
Ah, great point. I'm seeing that this is indeed how we have it set up.

And what you describe makes sense, `hubot-slack` is an adapter for the `hubot` service, not an actual drop in replacement itself.

Going to close because that's completely on point :+1: Thanks :smile:
