### ISSUE TITLE
re-reading messages after Slack outage

### ISSUE THREAD

**Issue by justmiles** [slackhq/hubot-slack#257]
I'm hoping I'm not the only one that experienced this after today's Slack outage. We use Hubot for various services where I work and pushed a minuscule script today requiring a restart. Upon restart, all the messages sent to our hubot instance since the outage began were sent again (hubot was up and running all day). It is as if Slack considered them unread. Needless to say, every one of these commands were re-processed. Some sending emails and others spamming the channels with irrelevant information.  

Any ideas on why this happened? Should we consider adding some middleware to assert the message timestamp is within range of the current timestamp before processing the command? Did anyone else experience this?

Appreciate your thoughts

**Comment by evansolomon** [comment]
I don't have much of an answer, but just wanted to not that the desktop slack client seemed to have similar problems marking old messages as unread.

**Comment by DEGoodmanWilson** [comment]
This was almost certainly a hiccup in our backend, I'm sorry to say. Adding de-dupe logic to https://github.com/slackhq/node-slack-sdk is almost certainly the right way forward on this, rather than attacking the problem here. Closing this issue, and opening one here:
https://github.com/slackhq/node-slack-sdk/issues/238
