### ISSUE TITLE
Hubot with slack adapter does not work locally

### ISSUE THREAD

**Issue by aliso** [slackhq/hubot-slack#258]
I have hubot integrated with Slack via Heroku, where it works as expected. If I run hubot locally with the default adapter, that works. However, if I try to run hubot locally with the slack adapter, I never get a prompt. I'm using the same command given in the readme:

    HUBOT_SLACK_TOKEN=xxxxxxxxxxx ./bin/hubot --adapter slack

I get the following output:

```
INFO Connecting...
INFO Logged in as hubot of XXXXXX, but not yet connected
INFO Slack client now connected
INFO hubot-redis-brain: Using default redis on localhost:6379
INFO hubot-redis-brain: Data for hubot brain retrieved from Redis
```

After that, nothing. I hit return and still no prompt appears. I can type anything and nothing happens. If I leave the window open long enough, I see the keepalive ping:

```
INFO keepalive ping
INFO keepalive pong: 200 OK
```

I have googled this issue to death and I can't find anyone in a similar boat. What could be going on?

**Comment by evansolomon** [comment]
That output looks more or less correct. I don't think you're supposed to get a prompt. What sort of prompt are you expecting?

**Comment by aliso** [comment]
I guess I'm confused. Where am I supposed to put commands to test the bot when I run it locally?

**Comment by evansolomon** [comment]
That command will connect to slack just like if you had run it on a server. So you can type stuff into Slack and the messages will be routed to wherever the bot is connected (locally or elsewhere) the same way they normally would.

If you actually want to use a shell to type messages then you can skip Slack completely and use separate adapter https://github.com/github/hubot/blob/master/docs/adapters/shell.md

If you want to use Slack-specific features and test locally but not type a bunch of nonsense that others can see, I usually either (1) use a DM with the hubot or (2) use a separate slack team. In both of those cases you'd still type messages in Slack, not a shell.

**Comment by aliso** [comment]
Thank you. I didn't realize it was taking over the same Slack connection as the Heroku instance, and that I'd test commands right in Slack. That makes sense. Does that mean my local hubot is replacing the Heroku one for every user on that Slack team?

I'm really new to hubot scripting, if you couldn't tell already.

**Comment by evansolomon** [comment]
> Does that mean my local hubot is replacing the Heroku one for every user on that Slack team?

Not really. Multiple instances of the "same" bot can be connected at once. It's like a (human) user having multiple clients open. The main difference is that the bot will likely just duplicate all of its actions because each process is acting independently, so you may end up with chat that looks like this.

```
User > Ping
Bot > Pong
Bot > Pong
```

Using a separate Slack team would probably be the easiest way to completely avoid that.

**Comment by aliso** [comment]
Thanks so much for your help on this. I set up a separate team and testing is going great!

**Comment by pkennel** [comment]
Just wanted to leave a note to help others since this the first google result for "hubot slack adapter local testing."  I recently did some local testing and found it very helpful to run hubot with the slack adapter a la `./bin/hubot --adapter slack` (with all the appropriate environment vars/creds to actually connect back to slack, and then in another shell curl that hubot on `:8080`.  e.g. `curl -X POST http://localhost:8080/hubot/slack-webhook --data "token=<SAME_VALUE_AS_HUBOT_SLACK_TOKEN>&text=hubot ping&user_id=U0QVAWDTR&user_name=dhowser&channel_name=testing"`.   Again just leaving this here as a bread crumb for others looking to do the same, sorry to re-activate this thread!
