### ISSUE TITLE
Message lost when bot is busy

### ISSUE THREAD

**Issue by Roooooo** [slackhq/hubot-slack#340]
Hello,

I'm trying processing some really big data remotely with slack but when the bot is busy on processing some message, bot will ignore any message from slack. I would like to know if there is a solution that can form incoming message into a queue so that we can deal with them later.

For an example, add following codes into scripts and bot will ignore any messages for 10 seconds when bot received a "foo".
```
robot.respond /foo/, (res) ->
  start = new Date.getTime()
  continue while new Data().getTime() - start < 10000
```

Thanks.

**Comment by DEGoodmanWilson** [comment]
This is an unfortunate side effect of using a single-threaded language and framework for doing realtime processing of event streams. Your only options are to move your big data processing into something more async friendly by breaking the upload into chunks so that you can handle incoming events in the middle, I'm sorry to say. How are you handling the big uploads now? My bet is there is a module out there somewhere that can assist.
