### ISSUE TITLE
Edit last message

### ISSUE THREAD

**Issue by lukerollans** [slackhq/hubot-slack#91]
Much the same as pressing Up (or of course, clicking "Edit") to edit the last message, I'm wondering if it's possible to do that programmatically within hubot or the adapter.

Would be stellar if it's possible.

Does anyone have any ideas?

**Comment by paulhammond** [comment]
thanks to slackhq/node-slack-client#14, the next version of node-slack-client will have the ability to edit messages. The only question left is how we'd implement this inside hubot's framework!

**Comment by fabianthoma** [comment]
As I've already commented on my pull request on node-slack-client, you get
the message object passed back, thanks to coffee script awesomeness you get
it passed through all hubot and node-slack-client methods, not entirely
sure if I changed something in hubot-slack, I'll check that when I get home.
You'd then just save the message object and modify it when you need to.
Am 31.01.2015 02:03 schrieb "Paul Hammond" <notifications@github.com>:

**Comment by id0Sch** [comment]
@paulhammond hi, just wondering; was this ever implemented? if not, how can I use it anyways?
I couldn't find a way and i really need to update sent messages
thanks

**Comment by gonstr** [comment]
Would also really like to know how to update messages. Been digging through documentation and PRs and can't figure out how.

**Comment by aoberoi** [comment]
i can shed some light on this. there's two problems that i see:
1. this adapter uses the RTM API for Slack. the only way to update a message is to use Web API method [`chat.update`](https://api.slack.com/methods/chat.update).
2. in order to use `chat.update`, you must know the message's `channel` and `ts` properties.

the first problem is pretty easy to solve, because you can create your own `WebClient` object. first you would `npm install --save @slack/client` in your project, then add a few lines into your script, like so:

```coffeescript
# import the Web client code from the node-slack-sdk
{WebClient} = require '@slack/client'

module.exports = (robot) ->
  # instantiate a Web client using the same bot token as the internal RTM client
  web = new WebClient(robot.adapter.client.rtm.token)

  # the rest of your script follows...
```

the second problem is a little harder to solve. once a message is already sent, the adapter needs to return that message to your code so you can use the `channel` and `ts` values. unfortunately, the adapter doesn't currently support this, but its close. it looks like the `SlackBot#send` method needs to detect whether the last item in `messages...` is a function, and if so use that as the callback. i think its worth making a new issue to track this feature, so i'm opening #473.

**Comment by gonstr** [comment]
Thanks @aoberoi 

If I used the WebClient to send the initial message instead of using the hubot API's, would I not be able to then get the channel and ts values?
